INSERT INTO toolset_inventory ("key","name","domain",label_dict,description_dict,api_key,"type",adapter_type,enabled,credit_billing,deleted_at) VALUES
	 ('defapi_sora2','DefAPI Sora 2 Video','https://defapi.org','{"en":"Sora 2 Video Generation","zh-CN":"Sora 2 视频生成"}','{"en":"Generate high-quality videos with audio using OpenAI Sora 2 model via DefAPI. Supports text-to-video and optional image-to-video generation.","zh-CN":"通过 DefAPI 使用 OpenAI Sora 2 模型生成高质量带音频视频。支持文生视频和可选的图生视频。"}',NULL,'regular','http',true,'{"defapi-sora2-text-to-video":30}',NULL)
ON CONFLICT ("key") DO NOTHING;

INSERT INTO toolsets (toolset_id,is_global,uid,"name","key",auth_type,auth_data,config,enabled,credit_billing,deleted_at,uninstalled) VALUES
	 ('ts-defapi-sora2-global-01',true,'','Sora 2 Video Generation','defapi_sora2','credentials',NULL,NULL,true,NULL,NULL,false)
ON CONFLICT ("toolset_id") DO NOTHING;

INSERT INTO tool_methods (inventory_key,version_id,"name",description,endpoint,http_method,request_schema,response_schema,adapter_type,adapter_config,enabled,deleted_at) VALUES
	 ('defapi_sora2',1,'defapi-sora2-text-to-video','Generate high-quality videos with synchronized audio using OpenAI Sora 2 model via DefAPI. Create videos from text prompts describing desired scenes, actions, and visual styles. Optionally provide a single reference image to guide the video generation. Supports 10s (default), 15s, and 25s (sora-2-pro only) durations with 16:9 widescreen or 9:16 vertical aspect ratios.','https://api.defapi.org/api/sora2/gen','POST','{"type":"object","description":"Generate videos using OpenAI Sora 2 model via DefAPI. Supports text-to-video and optional image-to-video generation with audio.","properties":{"prompt":{"type":"string","description":"REQUIRED. Text prompt describing the video to generate. Be specific about the desired scene, motion, characters, visual style, and audio. Example: ''A golden retriever playing on a sunny beach with waves gently crashing in the background, cinematic 4K quality''"},"model":{"type":"string","description":"AI model to use for video generation. Options: sora-2 (standard, default), sora-2-pro (higher quality, supports 25s duration). Default: ''sora-2''","enum":["sora-2","sora-2-pro"],"default":"sora-2"},"images":{"type":"array","maxItems":1,"items":{"type":"string","format":"url","isResource":true,"description":"Reference image URL. Accept fileId format (e.g., ''df-xxx'') which will be resolved to a URL automatically."},"description":"Optional. Provide a single reference image to guide the video generation. Maximum 1 image. The model will animate the image based on the text prompt."},"duration":{"type":"string","description":"Duration of the generated video in seconds. Options: 10 (default, $0.175), 15 ($0.20), 25 (only sora-2-pro). Default: ''10''","enum":["10","15","25"],"default":"10"},"aspect_ratio":{"type":"string","description":"Aspect ratio of the generated video. Options: 16:9 (widescreen, default), 9:16 (vertical for mobile). Default: ''16:9''","enum":["16:9","9:16"],"default":"16:9"}},"required":["prompt"]}','{"type":"object","description":"DefAPI Sora 2 task result containing the generated video.","properties":{"task_id":{"type":"string","description":"Unique task identifier"},"status":{"type":"string","description":"Task completion status"},"result":{"type":"object","description":"Generated video result","properties":{"video":{"type":"string","description":"URL to download the generated video (MP4 format with audio)","isResource":true,"format":"url"}},"required":["video"]},"consumed":{"type":"string","description":"Credits consumed for this generation"},"created_at":{"type":"string","description":"Task creation timestamp"}},"required":["task_id","status","result"]}','http','{"headers":{"Authorization":"Bearer ${apiKey}","Content-Type":"application/json"},"timeout":300000,"polling":{"statusUrl":"https://api.defapi.org/api/task/query?task_id={id}","maxWaitSeconds":1800,"intervalSeconds":10}}',true,NULL)
ON CONFLICT ("inventory_key", "name", "version_id") DO NOTHING;
